#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyNhanSu")]
	public partial class DataQLNSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    partial void InserttblNhanVien(tblNhanVien instance);
    partial void UpdatetblNhanVien(tblNhanVien instance);
    partial void DeletetblNhanVien(tblNhanVien instance);
    #endregion
		
		public DataQLNSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyNhanSuConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLNSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLNSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLNSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLNSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		public System.Data.Linq.Table<tblNhanVien> tblNhanViens
		{
			get
			{
				return this.GetTable<tblNhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUser")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _username;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public tblUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(30)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(30)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhanVien")]
	public partial class tblNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _QueQuan;
		
		private string _CMND;
		
		private string _DanToc;
		
		private string _TonGiao;
		
		private string _QuocTich;
		
		private string _TTHonNhan;
		
		private string _DiaChiThuongTru;
		
		private string _NoiOHienNay;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _TTSucKhoe;
		
		private System.Nullable<decimal> _ChieuCao;
		
		private System.Nullable<decimal> _CanNang;
		
		private System.Nullable<System.DateTime> _NgayTuyenDung;
		
		private string _HinhThucTuyenDung;
		
		private string _MaPhongBan;
		
		private string _MaChucVu;
		
		private string _ViTriTuyenDung;
		
		private string _TrinhDoHocVan;
		
		private string _TrinhDoChuyenMon;
		
		private string _HinhThucDaoTao;
		
		private string _TrinhDoNgoaiNgu;
		
		private string _TrinhDoTinHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnTonGiaoChanging(string value);
    partial void OnTonGiaoChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    partial void OnTTHonNhanChanging(string value);
    partial void OnTTHonNhanChanged();
    partial void OnDiaChiThuongTruChanging(string value);
    partial void OnDiaChiThuongTruChanged();
    partial void OnNoiOHienNayChanging(string value);
    partial void OnNoiOHienNayChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTTSucKhoeChanging(string value);
    partial void OnTTSucKhoeChanged();
    partial void OnChieuCaoChanging(System.Nullable<decimal> value);
    partial void OnChieuCaoChanged();
    partial void OnCanNangChanging(System.Nullable<decimal> value);
    partial void OnCanNangChanged();
    partial void OnNgayTuyenDungChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTuyenDungChanged();
    partial void OnHinhThucTuyenDungChanging(string value);
    partial void OnHinhThucTuyenDungChanged();
    partial void OnMaPhongBanChanging(string value);
    partial void OnMaPhongBanChanged();
    partial void OnMaChucVuChanging(string value);
    partial void OnMaChucVuChanged();
    partial void OnViTriTuyenDungChanging(string value);
    partial void OnViTriTuyenDungChanged();
    partial void OnTrinhDoHocVanChanging(string value);
    partial void OnTrinhDoHocVanChanged();
    partial void OnTrinhDoChuyenMonChanging(string value);
    partial void OnTrinhDoChuyenMonChanged();
    partial void OnHinhThucDaoTaoChanging(string value);
    partial void OnHinhThucDaoTaoChanged();
    partial void OnTrinhDoNgoaiNguChanging(string value);
    partial void OnTrinhDoNgoaiNguChanged();
    partial void OnTrinhDoTinHocChanging(string value);
    partial void OnTrinhDoTinHocChanged();
    #endregion
		
		public tblNhanVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(50)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(9)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(20)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonGiao", DbType="NVarChar(20)")]
		public string TonGiao
		{
			get
			{
				return this._TonGiao;
			}
			set
			{
				if ((this._TonGiao != value))
				{
					this.OnTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TonGiao = value;
					this.SendPropertyChanged("TonGiao");
					this.OnTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(20)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTHonNhan", DbType="NVarChar(20)")]
		public string TTHonNhan
		{
			get
			{
				return this._TTHonNhan;
			}
			set
			{
				if ((this._TTHonNhan != value))
				{
					this.OnTTHonNhanChanging(value);
					this.SendPropertyChanging();
					this._TTHonNhan = value;
					this.SendPropertyChanged("TTHonNhan");
					this.OnTTHonNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiThuongTru", DbType="NVarChar(50)")]
		public string DiaChiThuongTru
		{
			get
			{
				return this._DiaChiThuongTru;
			}
			set
			{
				if ((this._DiaChiThuongTru != value))
				{
					this.OnDiaChiThuongTruChanging(value);
					this.SendPropertyChanging();
					this._DiaChiThuongTru = value;
					this.SendPropertyChanged("DiaChiThuongTru");
					this.OnDiaChiThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiOHienNay", DbType="NVarChar(50)")]
		public string NoiOHienNay
		{
			get
			{
				return this._NoiOHienNay;
			}
			set
			{
				if ((this._NoiOHienNay != value))
				{
					this.OnNoiOHienNayChanging(value);
					this.SendPropertyChanging();
					this._NoiOHienNay = value;
					this.SendPropertyChanged("NoiOHienNay");
					this.OnNoiOHienNayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTSucKhoe", DbType="NVarChar(30)")]
		public string TTSucKhoe
		{
			get
			{
				return this._TTSucKhoe;
			}
			set
			{
				if ((this._TTSucKhoe != value))
				{
					this.OnTTSucKhoeChanging(value);
					this.SendPropertyChanging();
					this._TTSucKhoe = value;
					this.SendPropertyChanged("TTSucKhoe");
					this.OnTTSucKhoeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuCao", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ChieuCao
		{
			get
			{
				return this._ChieuCao;
			}
			set
			{
				if ((this._ChieuCao != value))
				{
					this.OnChieuCaoChanging(value);
					this.SendPropertyChanging();
					this._ChieuCao = value;
					this.SendPropertyChanged("ChieuCao");
					this.OnChieuCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this.OnCanNangChanging(value);
					this.SendPropertyChanging();
					this._CanNang = value;
					this.SendPropertyChanged("CanNang");
					this.OnCanNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTuyenDung", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTuyenDung
		{
			get
			{
				return this._NgayTuyenDung;
			}
			set
			{
				if ((this._NgayTuyenDung != value))
				{
					this.OnNgayTuyenDungChanging(value);
					this.SendPropertyChanging();
					this._NgayTuyenDung = value;
					this.SendPropertyChanged("NgayTuyenDung");
					this.OnNgayTuyenDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucTuyenDung", DbType="NVarChar(30)")]
		public string HinhThucTuyenDung
		{
			get
			{
				return this._HinhThucTuyenDung;
			}
			set
			{
				if ((this._HinhThucTuyenDung != value))
				{
					this.OnHinhThucTuyenDungChanging(value);
					this.SendPropertyChanging();
					this._HinhThucTuyenDung = value;
					this.SendPropertyChanged("HinhThucTuyenDung");
					this.OnHinhThucTuyenDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongBan", DbType="NVarChar(10)")]
		public string MaPhongBan
		{
			get
			{
				return this._MaPhongBan;
			}
			set
			{
				if ((this._MaPhongBan != value))
				{
					this.OnMaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaPhongBan = value;
					this.SendPropertyChanged("MaPhongBan");
					this.OnMaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", DbType="NVarChar(10)")]
		public string MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTriTuyenDung", DbType="NVarChar(50)")]
		public string ViTriTuyenDung
		{
			get
			{
				return this._ViTriTuyenDung;
			}
			set
			{
				if ((this._ViTriTuyenDung != value))
				{
					this.OnViTriTuyenDungChanging(value);
					this.SendPropertyChanging();
					this._ViTriTuyenDung = value;
					this.SendPropertyChanged("ViTriTuyenDung");
					this.OnViTriTuyenDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoHocVan", DbType="NVarChar(20)")]
		public string TrinhDoHocVan
		{
			get
			{
				return this._TrinhDoHocVan;
			}
			set
			{
				if ((this._TrinhDoHocVan != value))
				{
					this.OnTrinhDoHocVanChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoHocVan = value;
					this.SendPropertyChanged("TrinhDoHocVan");
					this.OnTrinhDoHocVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoChuyenMon", DbType="NVarChar(20)")]
		public string TrinhDoChuyenMon
		{
			get
			{
				return this._TrinhDoChuyenMon;
			}
			set
			{
				if ((this._TrinhDoChuyenMon != value))
				{
					this.OnTrinhDoChuyenMonChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoChuyenMon = value;
					this.SendPropertyChanged("TrinhDoChuyenMon");
					this.OnTrinhDoChuyenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDaoTao", DbType="NVarChar(50)")]
		public string HinhThucDaoTao
		{
			get
			{
				return this._HinhThucDaoTao;
			}
			set
			{
				if ((this._HinhThucDaoTao != value))
				{
					this.OnHinhThucDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._HinhThucDaoTao = value;
					this.SendPropertyChanged("HinhThucDaoTao");
					this.OnHinhThucDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoNgoaiNgu", DbType="NVarChar(20)")]
		public string TrinhDoNgoaiNgu
		{
			get
			{
				return this._TrinhDoNgoaiNgu;
			}
			set
			{
				if ((this._TrinhDoNgoaiNgu != value))
				{
					this.OnTrinhDoNgoaiNguChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoNgoaiNgu = value;
					this.SendPropertyChanged("TrinhDoNgoaiNgu");
					this.OnTrinhDoNgoaiNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoTinHoc", DbType="NVarChar(20)")]
		public string TrinhDoTinHoc
		{
			get
			{
				return this._TrinhDoTinHoc;
			}
			set
			{
				if ((this._TrinhDoTinHoc != value))
				{
					this.OnTrinhDoTinHocChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoTinHoc = value;
					this.SendPropertyChanged("TrinhDoTinHoc");
					this.OnTrinhDoTinHocChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
